remote_theme: alshedivat/al-folio

title: Jorge Omar López Martínez
first_name: Jorge
middle_name: Omar
last_name: López Martínez
lang: en
description: >
  Remote sensing & landscape ecology. Forest, urban & periurban ecosystems.
url: "https://lmjorgeomar.github.io"
baseurl: ""
icon: ⚛️
